<?php

namespace AppBundle\Repository;

/**
 * FromsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FromsRepository extends \Doctrine\ORM\EntityRepository
{
}
